# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Foro"
  url = "https://forum.heavenly.cl"
  weight = 5

[[main]]
  name = "Tienda"
  url = "https://store.heavenly.cl"
  weight = 1

[[main]]
  name = "Habilidades"
  url = "#habilidades"
  weight = 7

[[main]]
  name = "Proyectos"
  url = "#proyectos"
  weight = 9

[[main]]
  name = "Equipo"
  url = "#equipo"
  weight = 10

#[[main]]
#  name = "Proyectos"
#  url = "#proyectos"
#  weight = 30

[[main]]
  name = "Contacto"
  url = "#contacto"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
